<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace pavimus\sms\models\base;

use Yii;

/**
 * This is the base-model class for table "sms_batch".
 *
 * @property integer $id
 * @property integer $status
 * @property integer $cnt_total
 * @property integer $cnt_to_send
 * @property integer $cnt_sent
 * @property integer $cnt_errors
 * @property string $destinations
 * @property string $current_destination
 * @property string $text
 * @property string $dt_created
 * @property string $dt_processed
 * @property string $aliasModel
 */
abstract class SmsBatch extends \pavimus\sms\models\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sms_batch';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['status', 'cnt_total', 'cnt_to_send', 'cnt_sent', 'cnt_errors'], 'integer'],
            [['destinations', 'text', 'dt_created'], 'required'],
            [['destinations', 'current_destination', 'text'], 'string'],
            [['dt_created', 'dt_processed'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'status' => 'Status',
            'cnt_total' => 'Cnt Total',
            'cnt_to_send' => 'Cnt To Send',
            'cnt_sent' => 'Cnt Sent',
            'cnt_errors' => 'Cnt Errors',
            'destinations' => 'Destinations',
            'current_destination' => 'Current Destination',
            'text' => 'Text',
            'dt_created' => 'Dt Created',
            'dt_processed' => 'Dt Processed',
        ];
    }




}
